### ISSUE TITLE
Предметы в руках

### ISSUE THREAD

**Issue by sullome** [kmfreeminer/km-freeminer-mods#35]
Нужно сделать, чтобы были видимыми

**Comment by vegasd** [comment]
Нужно сделать, чтобы были видимыми и от первого лица тоже предметы, которые экипированы в руки, а не выделенные на хотбаре.

**Comment by sullome** [comment]
https://github.com/sullome/km-freeminer-mods/issues/27#issuecomment-228621826

**Comment by sullome** [comment]
> Нужно сделать, чтобы были видимыми и от первого лица тоже предметы, которые экипированы в руки, а не выделенные на хотбаре.
To be investigated

**Comment by sullome** [comment]
От первого лица отображается wielditem. Это такой вот особый предмет для игры — именно он «используется» по ПКМ и ЛКМ и всё такое прочее. Так что сделать так, чтобы отображался (от первого лица) один предмет, а использовался другой — можно только как-то так:
убрать из инвентаря лист main (это вот собсно hotbar). Его можно в целом и переназвать, это фиг с ним. Далее нужно будет переопределить стандартные функции подбирания предметов и т.д. — тоже фиг с ним. Проблемная фишка — переопределить функции ПКМ и ЛКМ. Нужно будет в них указывать, какой предмет реально использовать, вместо того который как бы wielditem. Для этого придётся выделить специальную ячейку, в которую игроку нужно будет самому предмет пихать (да, скроллинг колёсиком придётся убрать, так как это автоматически меняет wielditem).

**Comment by sullome** [comment]
>‎[19:01:08] ‎AnQay‎: да, лучше бы сделать, чтобы отображалось то, что вставлено в слот руки. Но раз это так трудозатратно, давай пока просто уберём вообще.
‎[19:01:22] ‎AnQay‎: Что ты ставишь, видно по хотбару выделением
‎[19:01:23] ‎AnQay‎: и норм
‎[19:01:48] ‎AnQay‎: healthbar тоже надо убрать
‎[19:02:01] ‎AnQay‎: и заменитьь heart.png на один пиксель чёрное-белый
‎[19:02:37] ‎sullome‎: Да можно и вообще убрать...
‎[19:02:58] ‎AnQay‎: Ну если ошибок не будет, то убрать

Сделано: 27a82dc
